---
name: Esquivando obstáculos
locale: es
type: practice
beta: false
teacher_info: ''
language: gobstones
id_format: "%05d"
order:
- 11
- 20
- 18
- 19
- 12
- 13
- 14
- 15
- 21
- 16
- 17
- 22
private: false
